name: manual workflow
on:
   push: 
   workflow_dispatch:
     inputs:
       abc: 
         description: for testing
         required: true
         default: aman
         type: string
       xyz:
         description: for 2nd test

jobs:
   build:
     runs-on: ubuntu-latest
     continue-on-error: True
     env:
        First_Name: aman
        Last_Name: kumar
     steps:
       - name: checkout
         uses: actions/checkout@v3
       - name: run command
         run: |
            echo "Hello ${{ github.event.inputs.abc }}"
            eco "Hello ${{ github.event.inputs.xyz }}"
            echo "Hello ${{ env.First_Name }} $Last_Name"
            echo "Hello $Last_Name
