name: manual workflow
on:
   workflow_dispatch:
     inputs:
       abc: 
         description: for testing
         required: true
         default: aman
         type: string
       xyz:
         description: for 2nd test
env:
  First_Name: aman
  Last_Name: kumar      

jobs:
   build:
     runs-on: ubuntu-latest
     continue-on-error: True
     steps:
       - name: checkout
         uses: actions/checkout@v3
       - name: run command
         continue-on-error: True
         run: |
            echo "Hello ${{ github.event.inputs.abc }}"
            echo "Hello ${{ github.event.inputs.xyz }}"
       - name: first-last name     
         run: |   
            echo "Hello ${{ env.First_Name }} $Last_Name"
            echo "Hello $Last_Name"

   test:
      needs: build
      runs-on: ubuntu-latest
      env:
        First_Name: AArush
        Last_Name: Deepika
      steps:
       - name: checkout
         uses: actions/checkout@v3
       - name: run command
         run: |
            echo "Hello ${{ github.event.inputs.abc }}"
            echo "Hello ${{ github.event.inputs.xyz }}"
            echo "Hello ${{ env.First_Name }} $Last_Name"
            echo "Hello $Last_Name" 


